// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Github() {
    driver.Navigate().GoToUrl("https://github.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1296, 1000);
    {
      var element = driver.FindElement(By.CssSelector(".btn-sm:nth-child(8)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.LinkText("molokolip/alx-low_level_programming")).Click();
    {
      var element = driver.FindElement(By.LinkText("molokolip/alx-system_engineering-devops"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.LinkText("0x00-hello_world")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.CssSelector(".d-none .js-path-segment span")).Click();
    driver.FindElement(By.LinkText("molokolip")).Click();
    driver.FindElement(By.CssSelector(".mb-3:nth-child(5) .repo")).Click();
    driver.FindElement(By.CssSelector(".input-group-button > .btn")).Click();
  }
}
